/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AvisoLegalRouteImport } from './routes/aviso-legal'
import { Route as ComoFuncionaRouteImport } from './routes/como-funciona'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as MisAntojosRouteImport } from './routes/mis-antojos'
import { Route as PrivacidadRouteImport } from './routes/privacidad'
import { Route as ResultadosRouteImport } from './routes/resultados'
import { Route as SobreNosotrosRouteImport } from './routes/sobre-nosotros'
import { Route as TerminosRouteImport } from './routes/terminos'
import { Route as OriginalSlugRouteImport } from './routes/original.$slug'
import { Route as ProductoSlugRouteImport } from './routes/producto.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AvisoLegalRoute = AvisoLegalRouteImport.update({
  id: '/aviso-legal',
  path: '/aviso-legal',
  getParentRoute: () => rootRouteImport,
} as any)
const ComoFuncionaRoute = ComoFuncionaRouteImport.update({
  id: '/como-funciona',
  path: '/como-funciona',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const MisAntojosRoute = MisAntojosRouteImport.update({
  id: '/mis-antojos',
  path: '/mis-antojos',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadRoute = PrivacidadRouteImport.update({
  id: '/privacidad',
  path: '/privacidad',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultadosRoute = ResultadosRouteImport.update({
  id: '/resultados',
  path: '/resultados',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreNosotrosRoute = SobreNosotrosRouteImport.update({
  id: '/sobre-nosotros',
  path: '/sobre-nosotros',
  getParentRoute: () => rootRouteImport,
} as any)
const TerminosRoute = TerminosRouteImport.update({
  id: '/terminos',
  path: '/terminos',
  getParentRoute: () => rootRouteImport,
} as any)
const OriginalSlugRoute = OriginalSlugRouteImport.update({
  id: '/original/$slug',
  path: '/original/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductoSlugRoute = ProductoSlugRouteImport.update({
  id: '/producto/$slug',
  path: '/producto/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aviso-legal': typeof AvisoLegalRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/contacto': typeof ContactoRoute
  '/cookies': typeof CookiesRoute
  '/mis-antojos': typeof MisAntojosRoute
  '/privacidad': typeof PrivacidadRoute
  '/resultados': typeof ResultadosRoute
  '/sobre-nosotros': typeof SobreNosotrosRoute
  '/terminos': typeof TerminosRoute
  '/original/$slug': typeof OriginalSlugRoute
  '/producto/$slug': typeof ProductoSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aviso-legal': typeof AvisoLegalRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/contacto': typeof ContactoRoute
  '/cookies': typeof CookiesRoute
  '/mis-antojos': typeof MisAntojosRoute
  '/privacidad': typeof PrivacidadRoute
  '/resultados': typeof ResultadosRoute
  '/sobre-nosotros': typeof SobreNosotrosRoute
  '/terminos': typeof TerminosRoute
  '/original/$slug': typeof OriginalSlugRoute
  '/producto/$slug': typeof ProductoSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aviso-legal': typeof AvisoLegalRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/contacto': typeof ContactoRoute
  '/cookies': typeof CookiesRoute
  '/mis-antojos': typeof MisAntojosRoute
  '/privacidad': typeof PrivacidadRoute
  '/resultados': typeof ResultadosRoute
  '/sobre-nosotros': typeof SobreNosotrosRoute
  '/terminos': typeof TerminosRoute
  '/original/$slug': typeof OriginalSlugRoute
  '/producto/$slug': typeof ProductoSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aviso-legal'
    | '/como-funciona'
    | '/contacto'
    | '/cookies'
    | '/mis-antojos'
    | '/privacidad'
    | '/resultados'
    | '/sobre-nosotros'
    | '/terminos'
    | '/original/$slug'
    | '/producto/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aviso-legal'
    | '/como-funciona'
    | '/contacto'
    | '/cookies'
    | '/mis-antojos'
    | '/privacidad'
    | '/resultados'
    | '/sobre-nosotros'
    | '/terminos'
    | '/original/$slug'
    | '/producto/$slug'
  id:
    | '__root__'
    | '/'
    | '/aviso-legal'
    | '/como-funciona'
    | '/contacto'
    | '/cookies'
    | '/mis-antojos'
    | '/privacidad'
    | '/resultados'
    | '/sobre-nosotros'
    | '/terminos'
    | '/original/$slug'
    | '/producto/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AvisoLegalRoute: typeof AvisoLegalRoute
  ComoFuncionaRoute: typeof ComoFuncionaRoute
  ContactoRoute: typeof ContactoRoute
  CookiesRoute: typeof CookiesRoute
  MisAntojosRoute: typeof MisAntojosRoute
  PrivacidadRoute: typeof PrivacidadRoute
  ResultadosRoute: typeof ResultadosRoute
  SobreNosotrosRoute: typeof SobreNosotrosRoute
  TerminosRoute: typeof TerminosRoute
  OriginalSlugRoute: typeof OriginalSlugRoute
  ProductoSlugRoute: typeof ProductoSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aviso-legal': {
      id: '/aviso-legal'
      path: '/aviso-legal'
      fullPath: '/aviso-legal'
      preLoaderRoute: typeof AvisoLegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/como-funciona': {
      id: '/como-funciona'
      path: '/como-funciona'
      fullPath: '/como-funciona'
      preLoaderRoute: typeof ComoFuncionaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mis-antojos': {
      id: '/mis-antojos'
      path: '/mis-antojos'
      fullPath: '/mis-antojos'
      preLoaderRoute: typeof MisAntojosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidad': {
      id: '/privacidad'
      path: '/privacidad'
      fullPath: '/privacidad'
      preLoaderRoute: typeof PrivacidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resultados': {
      id: '/resultados'
      path: '/resultados'
      fullPath: '/resultados'
      preLoaderRoute: typeof ResultadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre-nosotros': {
      id: '/sobre-nosotros'
      path: '/sobre-nosotros'
      fullPath: '/sobre-nosotros'
      preLoaderRoute: typeof SobreNosotrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terminos': {
      id: '/terminos'
      path: '/terminos'
      fullPath: '/terminos'
      preLoaderRoute: typeof TerminosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/original/$slug': {
      id: '/original/$slug'
      path: '/original/$slug'
      fullPath: '/original/$slug'
      preLoaderRoute: typeof OriginalSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/producto/$slug': {
      id: '/producto/$slug'
      path: '/producto/$slug'
      fullPath: '/producto/$slug'
      preLoaderRoute: typeof ProductoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AvisoLegalRoute: AvisoLegalRoute,
  ComoFuncionaRoute: ComoFuncionaRoute,
  ContactoRoute: ContactoRoute,
  CookiesRoute: CookiesRoute,
  MisAntojosRoute: MisAntojosRoute,
  PrivacidadRoute: PrivacidadRoute,
  ResultadosRoute: ResultadosRoute,
  SobreNosotrosRoute: SobreNosotrosRoute,
  TerminosRoute: TerminosRoute,
  OriginalSlugRoute: OriginalSlugRoute,
  ProductoSlugRoute: ProductoSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
